In [4]:
import torch
import tsensor as ts
from IPython.display import SVG, display
import sys

In [5]:
def show_svg(svg):
    display(SVG(svg))

In [6]:
x = torch.arange(4.0)
show_svg(ts.astviz('x', sys._getframe()).savefig('/tmp/ast.svg'))

<IPython.core.display.SVG object>

In [7]:
x.requires_grad_(True)
x.grad

In [8]:
y = 2 * torch.sum(x * x)

In [9]:
with ts.explain():
    x
    y
x, y

findfont: Font family ['Consolas'] not found. Falling back to DejaVu Sans.
findfont: Font family ['Arial'] not found. Falling back to DejaVu Sans.


(tensor([0., 1., 2., 3.], requires_grad=True),
 tensor(28., grad_fn=<MulBackward0>))

In [10]:
y.backward()
x.grad
x.grad == 4 * x

tensor([True, True, True, True])

In [11]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [12]:
x
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [13]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [14]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [15]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [16]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()
a.grad == d / a

tensor(True)